SystemJS.config({
  browserConfig: {
    "paths": {
      "npm:": "/jspm_packages/npm/",
      "aire": "dist/",
      "github:": "/jspm_packages/github/",
      "local:": "/jspm_packages/local/",
      "aire/": "src/"
    }
  },
  nodeConfig: {
    "paths": {
      "npm:": "jspm_packages/npm/",
      "github:": "jspm_packages/github/",
      "local:": "jspm_packages/local/",
      "aire/": "dist/",
      "aire-build/": "../../aire-build/"
    }
  },
  packages: {
    "aire": {
      "main": "index.js",
      "defaultExtension": "js"
    },
    "npm:aurelia-binding@2.1.7": {
      "map": {
        "aurelia-task-queue": "npm:aurelia-task-queue@1.3.1",
        "aurelia-logging": "npm:aurelia-logging@1.5.0",
        "aurelia-pal": "npm:aurelia-pal@1.8.0",
        "aurelia-metadata": "npm:aurelia-metadata@1.0.4"
      }
    },
    "npm:aurelia-fetch-client@1.7.0": {
      "map": {
        "aurelia-pal": "npm:aurelia-pal@1.8.0"
      }
    }
  },
  packageConfigPaths: [
    "npm:@*/*.json",
    "npm:*.json",
    "github:*/*.json"
  ],
  map: {
    "aurelia-animator-velocity": "npm:aurelia-animator-velocity@1.2.0",
    "aurelia-binding": "npm:aurelia-binding@2.1.7",
    "aurelia-bootstrapper": "npm:aurelia-bootstrapper@2.3.1",
    "aurelia-dependency-injection": "npm:aurelia-dependency-injection@1.4.1",
    "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.1",
    "aurelia-fetch-client": "npm:aurelia-fetch-client@1.7.0",
    "aurelia-framework": "npm:aurelia-framework@1.3.0",
    "aurelia-history": "npm:aurelia-history@1.1.0",
    "aurelia-history-browser": "npm:aurelia-history-browser@1.2.0",
    "aurelia-loader": "npm:aurelia-loader@1.0.0",
    "aurelia-loader-default": "npm:aurelia-loader-default@1.1.0",
    "aurelia-logging": "npm:aurelia-logging@1.5.0",
    "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0",
    "aurelia-metadata": "npm:aurelia-metadata@1.0.4",
    "aurelia-pal": "npm:aurelia-pal@1.8.0",
    "aurelia-pal-browser": "npm:aurelia-pal-browser@1.8.0",
    "aurelia-path": "npm:aurelia-path@1.1.1",
    "aurelia-polyfills": "npm:aurelia-polyfills@1.3.0",
    "aurelia-route-recognizer": "npm:aurelia-route-recognizer@1.3.1",
    "aurelia-router": "npm:aurelia-router@1.6.3",
    "aurelia-task-queue": "npm:aurelia-task-queue@1.3.1",
    "aurelia-templating": "npm:aurelia-templating@1.10.1",
    "aurelia-templating-binding": "npm:aurelia-templating-binding@1.5.2",
    "aurelia-templating-resources": "npm:aurelia-templating-resources@1.7.1",
    "aurelia-templating-router": "npm:aurelia-templating-router@1.3.3",
    "child_process": "npm:jspm-nodelibs-child_process@0.2.1",
    "fs": "npm:jspm-nodelibs-fs@0.2.1",
    "path": "npm:jspm-nodelibs-path@0.2.3",
    "process": "npm:jspm-nodelibs-process@0.2.1",
    "text": "github:systemjs/plugin-text@0.0.11",
    "uikit": "npm:uikit@3.0.0-rc.25",
    "velocity-animate": "npm:velocity-animate@1.5.2"
  },
  bundles: {
    "aire/aurelia.js": [
      "npm:aurelia-binding@2.1.7.json",
      "npm:aurelia-binding@2.1.7/aurelia-binding.js",
      "npm:aurelia-dependency-injection@1.4.1.json",
      "npm:aurelia-dependency-injection@1.4.1/aurelia-dependency-injection.js",
      "npm:aurelia-framework@1.3.0.json",
      "npm:aurelia-framework@1.3.0/aurelia-framework.js",
      "npm:aurelia-loader@1.0.0.json",
      "npm:aurelia-loader@1.0.0/aurelia-loader.js",
      "npm:aurelia-logging@1.5.0.json",
      "npm:aurelia-logging@1.5.0/aurelia-logging.js",
      "npm:aurelia-metadata@1.0.4.json",
      "npm:aurelia-metadata@1.0.4/aurelia-metadata.js",
      "npm:aurelia-pal@1.8.0.json",
      "npm:aurelia-pal@1.8.0/aurelia-pal.js",
      "npm:aurelia-path@1.1.1.json",
      "npm:aurelia-path@1.1.1/aurelia-path.js",
      "npm:aurelia-task-queue@1.3.1.json",
      "npm:aurelia-task-queue@1.3.1/aurelia-task-queue.js",
      "npm:aurelia-templating@1.10.1.json",
      "npm:aurelia-templating@1.10.1/aurelia-templating.js"
    ],
    "aire/app-build.js": [
      "aire/accordion/accordion-item.js",
      "aire/accordion/accordion-item.spec.js",
      "aire/accordion/accordion.js",
      "aire/accordion/accordion.spec.js",
      "aire/aire.js",
      "aire/application/application.js",
      "aire/application/body.js",
      "aire/application/header.js",
      "aire/application/router-view.js",
      "aire/button/basebutton.js",
      "aire/button/button.js",
      "aire/button/button.spec.js",
      "aire/button/fab.js",
      "aire/button/fab.spec.js",
      "aire/card/basiccard.js",
      "aire/card/basiccard.spec.js",
      "aire/card/card.js",
      "aire/card/dividedcard.js",
      "aire/card/dividedcard.spec.js",
      "aire/card/help/en/basic-card/styles/example.js",
      "aire/card/help/en/basic-card/usage/example.js",
      "aire/card/help/en/divided-card/styles/example.js",
      "aire/card/help/en/divided-card/usage/example.js",
      "aire/core.js",
      "aire/core/application.js",
      "aire/core/application.spec.js",
      "aire/core/base58.js",
      "aire/core/decorators.js",
      "aire/core/dom.js",
      "aire/core/dom.spec.js",
      "aire/core/identifiers.js",
      "aire/core/lang.js",
      "aire/core/range.js",
      "aire/core/uuid.js",
      "aire/core/widget.js",
      "aire/dropdown/dropdown.js",
      "aire/dropdown/dropdown.spec.js",
      "aire/events.js",
      "aire/form/checkbox.js",
      "aire/form/checkbox.spec.js",
      "aire/form/element.js",
      "aire/form/input.js",
      "aire/form/input.spec.js",
      "aire/form/multielement.js",
      "aire/form/radio.js",
      "aire/form/radio.spec.js",
      "aire/form/range.js",
      "aire/form/range.spec.js",
      "aire/form/select.js",
      "aire/form/select.spec.js",
      "aire/form/textarea.js",
      "aire/form/textarea.spec.js",
      "aire/icon/icon.js",
      "aire/icon/icon.spec.js",
      "aire/init.js",
      "aire/init/configure-logging.js",
      "aire/init/init.spec.js",
      "aire/init/register-animations.js",
      "aire/loader/loader.js",
      "aire/loader/loader.spec.js",
      "aire/nav/nav.js",
      "aire/nav/nav.spec.js",
      "aire/navbar/item.js",
      "aire/navbar/item.spec.js",
      "aire/navbar/navbar.js",
      "aire/navbar/navbar.spec.js",
      "aire/navbar/section.js",
      "aire/navbar/section.spec.js",
      "aire/offcanvas/offcanvas.js",
      "aire/offcanvas/offcanvas.spec.js",
      "aire/page/page.js",
      "aire/page/page.spec.js",
      "aire/search/search.js",
      "aire/search/search.spec.js",
      "aire/table/table.js",
      "aire/table/table.spec.js",
      "aire/tabs/tab-panel.js",
      "aire/tabs/tab-panel.spec.js",
      "aire/tabs/tab.js",
      "aire/tabs/tab.spec.js",
      "aire/test/render.js",
      "aire/test/setup.js",
      "aire/widget/widget-panel.js",
      "github:systemjs/plugin-text@0.0.11.json",
      "index.html!github:systemjs/plugin-text@0.0.11/text.js"
    ]
  }
});